AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0.2
  Exclude:
    - Gemfile
    - db/fixtures/**/*
    - db/schema.rb
    - db/migrate/*
    - 'app/view/**/*.erb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - spec/requests/api/v1/*
  NewCops : enable

Style/Documentation:
  Enabled: false